module.exports = [
    'https://en.wikipedia.org/wiki/Formula_One', 
    'https://en.wikipedia.org/wiki/Formula_One_racing',
    'https://simple.wikipedia.org/wiki/Formula_1',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_Grands_Prix',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_drivers',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_constructors',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_world_champions',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_grand_prix_winners',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_results',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_tracks',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_race_number',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_season',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_driver',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_constructor',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_grand_prix',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_race_type',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_race_distance',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_race_surface',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_race_year',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_race_circuit',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_race_date',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_race_location',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_race_time',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_race_season_and_driver',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_race_season_and_constructor',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_race_season_and_grand_prix',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_race_season_and_race_type',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_race_season_and_race_distance',
    'https://en.wikipedia.org/wiki/List_of_Formula_One_race_winners_by_race_season_and_race_surface',
    
  ];
  